// integration/apps/angular/src/app.component.ts
import '@gromlab/svg-sprites/viewer/element'

import { CUSTOM_ELEMENTS_SCHEMA, Component } from '@angular/core'

import { AppIcon } from './app-icons'
import { RemoteAppIcon } from './remote-app-icons'

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [AppIcon, RemoteAppIcon],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <main>
      <h1>Angular application builder</h1>
      <app-icon
        data-testid="icon"
        data-app="angular"
        icon="check"
        aria-label="Check icon"
        style="width:64px;height:64px;color:#16a34a;--icon-color-1:#16a34a"
      />
      <remote-app-icon
        data-testid="remote-icon"
        data-app="angular-remote"
        icon="check"
        aria-label="Remote check icon"
        style="width:64px;height:64px;color:#16a34a;--icon-color-1:#16a34a"
      />
      <gromlab-sprite-viewer
        [sources]="viewerSources"
        viewer-title="Angular Application Viewer"
      />
    </main>
  `,
})
export class AppComponent {
  readonly viewerSources = [
    () => import('./app-icons/.svg-sprite/svg-sprite.manifest.js'),
    () => import('./remote-app-icons/.svg-sprite/svg-sprite.manifest.js'),
  ]
}

// integration/apps/vue-vite/src/App.vue
<script setup>
import '@gromlab/svg-sprites/viewer/element'

import { AppIcon } from './app-icons/index.js'
import { RemoteAppIcon } from './remote-app-icons/index.js'

const viewerSources = [
  () => import('./app-icons/.svg-sprite/svg-sprite.manifest.js'),
  () => import('./remote-app-icons/.svg-sprite/svg-sprite.manifest.js'),
]
</script>

<template>
  <main>
    <h1>Vue + Vite</h1>
    <AppIcon
      data-testid="icon"
      data-app="vue-vite"
      icon="check"
      aria-label="Check icon"
      width="64"
      height="64"
      style="--icon-color-1: #16a34a"
    />
    <RemoteAppIcon
      data-testid="remote-icon"
      data-app="vue-vite-remote"
      icon="check"
      aria-label="Remote check icon"
      width="64"
      height="64"
      style="--icon-color-1: #16a34a"
    />
    <gromlab-sprite-viewer
      :sources="viewerSources"
      viewer-title="Vue Vite Viewer"
    />
  </main>
</template>

<style>
:root {
  font-family: system-ui, sans-serif;
  color: #172033;
  background: #fff;
}

body {
  margin: 0;
  padding: 40px;
}

gromlab-sprite-viewer {
  display: block;
  margin-top: 32px;
}
</style>
