// integration/apps/nuxt-webpack/app/app.vue
<script setup>
import { AppIcon } from '../src/app-icons/index.js'
import { RemoteAppIcon } from '../src/remote-app-icons/index.js'
</script>

<template>
  <main>
    <h1>Nuxt + Webpack</h1>
    <AppIcon
      data-testid="icon"
      data-app="nuxt-webpack"
      icon="check"
      aria-label="Check icon"
      width="64"
      height="64"
      style="--icon-color-1: #16a34a"
    />
    <RemoteAppIcon
      data-testid="remote-icon"
      data-app="nuxt-webpack-remote"
      icon="check"
      aria-label="Remote check icon"
      width="64"
      height="64"
      style="--icon-color-1: #16a34a"
    />
    <SpriteViewer />
  </main>
</template>

<style>
:root {
  font-family: system-ui, sans-serif;
  color: #172033;
  background: #fff;
}

body {
  margin: 0;
  padding: 40px;
}

gromlab-sprite-viewer {
  display: block;
  margin-top: 32px;
}
</style>

// integration/apps/next-app-webpack/app/page.tsx
import { AppIcon } from '../src/app-icons'
import { RemoteAppIcon } from '../src/remote-app-icons'
import { AppSpriteViewer } from './sprite-viewer'

export default function Page() {
  return (
    <main>
      <h1>Next.js App Router + Webpack</h1>
      <AppIcon
        data-testid="icon"
        data-app="next-app-webpack"
        icon="check"
        aria-label="Check icon"
        width={64}
        height={64}
        style={{ '--icon-color-1': '#16a34a' }}
      />
      <RemoteAppIcon
        data-testid="remote-icon"
        data-app="next-app-webpack-remote"
        icon="check"
        aria-label="Remote check icon"
        width={64}
        height={64}
        style={{ '--icon-color-1': '#16a34a' }}
      />
      <AppSpriteViewer />
    </main>
  )
}
