// integration/apps/react-webpack/src/main.tsx
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { SpriteViewer } from '@gromlab/svg-sprites/react'

import { AppIcon } from './app-icons'
import { RemoteAppIcon } from './remote-app-icons'
import './style.css'

const viewerSources = [
  () => import('./app-icons/.svg-sprite/svg-sprite.manifest.js'),
  () => import('./remote-app-icons/.svg-sprite/svg-sprite.manifest.js'),
] as const

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <main>
      <h1>React + Webpack</h1>
      <AppIcon
        data-testid="icon"
        data-app="react-webpack"
        icon="check"
        aria-label="Check icon"
        width={64}
        height={64}
        style={{ '--icon-color-1': '#16a34a' }}
      />
      <RemoteAppIcon
        data-testid="remote-icon"
        data-app="react-webpack-remote"
        icon="check"
        aria-label="Remote check icon"
        width={64}
        height={64}
        style={{ '--icon-color-1': '#16a34a' }}
      />
      <SpriteViewer sources={viewerSources} title="React Webpack Viewer" style={{ marginTop: 32 }} />
    </main>
  </StrictMode>,
)

// integration/apps/solid-webpack/src/main.jsx
import { onMount } from 'solid-js'
import { render } from 'solid-js/web'

import '@gromlab/svg-sprites/viewer/element'
import { AppIcon } from './app-icons/index.js'
import { RemoteAppIcon } from './remote-app-icons/index.js'
import './style.css'

const viewerSources = [
  () => import('./app-icons/.svg-sprite/svg-sprite.manifest.js'),
  () => import('./remote-app-icons/.svg-sprite/svg-sprite.manifest.js'),
]

function App() {
  let viewer

  onMount(() => {
    viewer.sources = viewerSources
  })

  return (
    <main>
      <h1>Solid + Webpack</h1>
      <AppIcon
        data-testid="icon"
        data-app="solid-webpack"
        icon="check"
        aria-label="Check icon"
        width={64}
        height={64}
        style={{ color: '#16a34a', '--icon-color-1': '#16a34a' }}
      />
      <RemoteAppIcon
        data-testid="remote-icon"
        data-app="solid-webpack-remote"
        icon="check"
        aria-label="Remote check icon"
        width={64}
        height={64}
        style={{ color: '#16a34a', '--icon-color-1': '#16a34a' }}
      />
      <gromlab-sprite-viewer ref={viewer} viewer-title="Solid Webpack Viewer" />
    </main>
  )
}

render(() => <App />, document.getElementById('root'))
