// integration/apps/react-vite/src/main.tsx
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'

import { IconsIcon } from './sprite'
import './style.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <main>
      <h1>React + Vite</h1>
      <IconsIcon
        data-testid="icon"
        data-app="react-vite"
        icon="check"
        aria-label="Check icon"
        width={64}
        height={64}
        style={{ '--icon-color-1': '#16a34a' }}
      />
    </main>
  </StrictMode>,
)

// integration/apps/solid-vite/src/main.tsx
import { render } from 'solid-js/web'

import './style.css'

function App() {
  return (
    <main>
      <h1>Solid + Vite</h1>
      <svg
        data-testid="icon"
        data-app="solid-vite"
        aria-label="Check icon"
        viewBox="0 0 24 24"
      >
        <use href="/sprites/icons.sprite.svg#check" />
      </svg>
    </main>
  )
}

render(() => <App />, document.getElementById('root')!)
