// integration/apps/react-vite/src/main.tsx
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { SpriteViewer } from '@gromlab/svg-sprites/react'

import { AppIcon } from './app-icons'
import { RemoteAppIcon } from './remote-app-icons'
import './style.css'

const viewerSources = [
  () => import('./app-icons/.svg-sprite/svg-sprite.manifest.js'),
  () => import('./remote-app-icons/.svg-sprite/svg-sprite.manifest.js'),
] as const

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <main>
      <h1>React + Vite</h1>
      <AppIcon
        data-testid="icon"
        data-app="react-vite"
        icon="check"
        aria-label="Check icon"
        width={64}
        height={64}
        style={{ '--icon-color-1': '#16a34a' }}
      />
      <RemoteAppIcon
        data-testid="remote-icon"
        data-app="react-vite-remote"
        icon="check"
        aria-label="Remote check icon"
        width={64}
        height={64}
        style={{ '--icon-color-1': '#16a34a' }}
      />
      <SpriteViewer sources={viewerSources} title="React Vite Viewer" style={{ marginTop: 32 }} />
    </main>
  </StrictMode>,
)

// integration/apps/solid-vite/src/main.jsx
import { onMount } from 'solid-js'
import { render } from 'solid-js/web'

import { AppIcon } from './app-icons'
import { RemoteAppIcon } from './remote-app-icons'
import './style.css'

function App() {
  let viewerHost

  onMount(async () => {
    await import('@gromlab/svg-sprites/viewer/element')
    const viewer = document.createElement('gromlab-sprite-viewer')
    viewer.viewerTitle = 'Solid Vite Viewer'
    viewer.sources = [
      () => import('./app-icons/.svg-sprite/svg-sprite.manifest.js'),
      () => import('./remote-app-icons/.svg-sprite/svg-sprite.manifest.js'),
    ]
    viewerHost.append(viewer)
  })

  return (
    <main>
      <h1>Solid + Vite</h1>
      <AppIcon
        data-testid="icon"
        data-app="solid-vite"
        icon="check"
        aria-label="Check icon"
        width={64}
        height={64}
        style={{ color: '#16a34a', '--icon-color-1': '#16a34a' }}
      />
      <RemoteAppIcon
        data-testid="remote-icon"
        data-app="solid-vite-remote"
        icon="check"
        aria-label="Remote check icon"
        width={64}
        height={64}
        style={{ color: '#16a34a', '--icon-color-1': '#16a34a' }}
      />
      <div class="viewer" ref={viewerHost} />
    </main>
  )
}

render(() => <App />, document.getElementById('root'))
