// integration/apps/solid-webpack/src/main.jsx
import { onMount } from 'solid-js'
import { render } from 'solid-js/web'

import '@gromlab/svg-sprites/viewer/element'
import { AppIcon } from './app-icons/index.js'
import { RemoteAppIcon } from './remote-app-icons/index.js'
import './style.css'

const viewerSources = [
  () => import('./app-icons/.svg-sprite/svg-sprite.manifest.js'),
  () => import('./remote-app-icons/.svg-sprite/svg-sprite.manifest.js'),
]

function App() {
  let viewer

  onMount(() => {
    viewer.sources = viewerSources
  })

  return (
    <main>
      <h1>Solid + Webpack</h1>
      <AppIcon
        data-testid="icon"
        data-app="solid-webpack"
        icon="check"
        aria-label="Check icon"
        width={64}
        height={64}
        style={{ color: '#16a34a', '--icon-color-1': '#16a34a' }}
      />
      <RemoteAppIcon
        data-testid="remote-icon"
        data-app="solid-webpack-remote"
        icon="check"
        aria-label="Remote check icon"
        width={64}
        height={64}
        style={{ color: '#16a34a', '--icon-color-1': '#16a34a' }}
      />
      <gromlab-sprite-viewer ref={viewer} viewer-title="Solid Webpack Viewer" />
    </main>
  )
}

render(() => <App />, document.getElementById('root'))

// integration/apps/angular-webpack/src/main.ts
import '@gromlab/svg-sprites/viewer/element'

import { CUSTOM_ELEMENTS_SCHEMA, Component } from '@angular/core'
import { bootstrapApplication } from '@angular/platform-browser'

import { AppIcon } from './app-icons'
import { RemoteAppIcon } from './remote-app-icons'
import './type-probe'

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [AppIcon, RemoteAppIcon],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <main>
      <h1>Angular + Webpack</h1>
      <app-icon
        data-testid="icon"
        data-app="angular-webpack"
        icon="check"
        aria-label="Check icon"
        style="width:64px;height:64px;color:#16a34a;--icon-color-1:#16a34a"
      />
      <remote-app-icon
        data-testid="remote-icon"
        data-app="angular-webpack-remote"
        icon="check"
        aria-label="Remote check icon"
        style="width:64px;height:64px;color:#16a34a;--icon-color-1:#16a34a"
      />
      <gromlab-sprite-viewer
        [sources]="viewerSources"
        viewer-title="Angular Webpack Viewer"
      />
    </main>
  `,
})
class AppComponent {
  readonly viewerSources = [
    () => import('./app-icons/.svg-sprite/svg-sprite.manifest.js'),
    () => import('./remote-app-icons/.svg-sprite/svg-sprite.manifest.js'),
  ]
}

bootstrapApplication(AppComponent).catch((error: unknown) => console.error(error))
